
spring:
  flyway:
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/bridge
    username: admin
    password: admin
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      show-sql: true
